<?php
/**
 * Created by yuxianjun001@icloud.com.
 * User: wuchen
 * Date: 2019/5/30
 * Time: 10:49
 */

namespace App\Http\Middleware\SuperAdmin;

use App\Http\Middleware\Common\BaseVerifyPermissions;
use App\Traits\ResponseTrait;
use Closure;

/**
 * 验证权限中间件
 * Class VerifyPermissions
 * @package App\Http\Middleware\Common
 */
class VerifyPermissions extends BaseVerifyPermissions
{
    use ResponseTrait;

    public function __construct()
    {

    }

    public function handle($request, Closure $next)
    {
        $request->guardName = config('permission.super_admin');//在不同的应用下，指定不同的guardName，与在不同的应用下的构造函数中指定guardName保持
        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }


}